# Generated by Django 3.1.2 on 2020-10-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_group_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
    ]
